image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/backend/.cache/pip"

before_script:
  - python --version
  - cd backend && pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - pytest tests/config.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
    - branches