image: python:latest

services:
  - postgres:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/backend/.cache/pip"
  POSTGRES_DB: bookdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_STRING: postgresql://$POSTGRES_USER@postgres:5432/$POSTGRES_DB

before_script:
  - python --version
  - cd backend && pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - pytest tests/config.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/backend/report.xml
  only:
    - branches
